### ISSUE TITLE
Teleport target rotation is off when using snap turning

### ISSUE THREAD

**Issue by mhenry07** [toji/xr-dinosaurs#4]
When using snap turning, the teleport target texture (dinosaur feet) sometimes displays with the wrong orientation.

I experienced the issue on Oculus Quest on both the Oculus browser and Firefox Reality, though I imagine it's an issue for all devices that support snap turning.

**Comment by toji** [comment]
Thanks! It's a known issue, but I haven't put much effort into fixing it because I wasn't sure if anyone was even using the teleport. Guess I have my answer. 😁

**Comment by mhenry07** [comment]
I didn't realize teleport had been added until I revisited the site today. I enjoyed being able to teleport around and it seems the performance has improved too. 👍

**Comment by toji** [comment]
Working beautifully now. Thank you!
