### ISSUE TITLE
Add a license do the project

### ISSUE THREAD

**Issue by pesader** [toji/xr-dinosaurs#6]
Hi! I would like to reuse some of the code in WebXR Dinossaurs but I noticed that the repository doesn't have a license. Would it be possible to add one?

Thanks in advance :)

**Comment by toji** [comment]
Done! The source files already had an MIT license embedded in the headers, but the fact that there wasn't a license at the root of the repo was just an oversight.

**Comment by pesader** [comment]
Ah, thank you so much for the clarification.

Happy rawring! 🦕
